{{- if and .Values.massdriver.metrics.enabled .Values.massdriver.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "massdriver.fullname" . }}-massdriver
  labels:
    {{- include "massdriver.labels" . | nindent 4 }}
    app.kubernetes.io/component: massdriver
    {{- with .Values.massdriver.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "massdriver.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: massdriver
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.massdriver.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.massdriver.metrics.serviceMonitor.scrapeTimeout }}
{{- end }}