apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "massdriver.fullname" . }}-s3proxy
  labels:
    {{- include "massdriver.labels" . | nindent 4 }}
    app.kubernetes.io/component: s3proxy
  {{- with .Values.massdriver.blobStorage.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
