apiVersion: v2
name: massdriver
description: Helm chart for deploying Massdriver
type: application
version: 0.0.20
appVersion: 1.2.4
icon: https://raw.githubusercontent.com/massdriver-cloud/helm-charts/main/charts/massdriver/icon.png

dependencies:
  - name: argo-workflows
    condition: argo-workflows.enabled
    version: 0.45.14
    repository: https://argoproj.github.io/argo-helm
  - name: minio
    condition: minio.enabled
    version: 5.4.0
    repository: https://charts.min.io/